include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
