name: doseminder
description: A medication dispenser mobile app controller. 
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  flutter_riverpod: ^2.4.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/

flutter_launcher_icons:
  android: true
  image_path: assets/icon-dark.png

flutter_native_splash:
  android: true
  image: assets/icon.png
  color: "#4169e1"

  android_12:
    image: assets/icon.png
    icon_background_color: "#4169e1"

  web: false
